### ISSUE TITLE
Lower Tuple

### ISSUE THREAD

**Issue by ksolana** [solana-labs/move#165]
Declared in: https://github.com/move-language/move/blob/main/language/move-model/src/ty.rs#L26

**Comment by nvjle** [comment]
Please add a test case example in the description. This was once a second-class value in Move (as mentioned here: https://move-language.github.io/move/tuples.html#tuples-and-unit ), which we already implement. I believe this issue is saying that the tuple has since been upgraded to a first-class value. If this is the case, the Move compiler should parse them  and generate bytecode that we can try.

**Comment by ksolana** [comment]
I can't find a testcase for this in move code base. we can close this for now.

**Comment by ksolana** [comment]
Tuples as supported by move is already handled: https://github.com/solana-labs/move/pull/105/files
