### ISSUE TITLE
[Bug] CI does not trigger checks if PR includes only test related changes

### ISSUE THREAD

**Issue by jcivlin** [solana-labs/move#336]
# 🐛 Bug
See example 
https://github.com/solana-labs/move/pull/335

**Comment by softalchemy** [comment]
@yihau

**Comment by dmakarov** [comment]
@yihau never mind the title of this issue. The problem is not related to whether PR includes only test related changes or not. I think the issue may be with the add-pr-link workflow. Somehow GH uses that workflow to populate the checks on the PR page maybe.

**Comment by dmakarov** [comment]
@yihau when more commits are pushed or force pushed to an existing PR, the add-pr-link workflow is not triggered, but the llvm-ci-pre-land workflow is triggered, and the checks appear on the PR page as expected. So it's definitely a problem with add-pr-link being triggered on PR creation.

**Comment by yihau** [comment]
checking 🫠

**Comment by jcivlin** [comment]
@dmakarov, I believe the good practice is to let the author of the issue to close it.

**Comment by dmakarov** [comment]
> @dmakarov, I believe the good practice is to let the author of the issue to close it.

@jcivlin  You can believe whatever you want. The issue was closed by GH automatically when I merged the PR that Yihau designated as resolving your issue. I did not close your issue. Learn how tools work before stating your believes.

**Comment by jcivlin** [comment]
I'm referencing to this 
![image](https://github.com/solana-labs/move/assets/30603832/1265de09-952a-4ec2-8ee0-2b84bdff3362)

And I do not understand why your answers are so condescended.

**Comment by dmakarov** [comment]
> I'm referencing to this ![image](https://user-images.githubusercontent.com/30603832/266462617-1265de09-952a-4ec2-8ee0-2b84bdff3362.png)
> 
> And I do not understand why your answers are so condescended.

That is what GH does when a user merges a PR that has a comment "Close #NNN" or "Resolve #NNN". I merged Yihau PR #339, which has a comment "Close #336". I merged Yihau's PR because Yihau doesn't have permissions to merge PRs in this repository. If Yihau merged his PR his name would appear as closing your issue. I personally did not close your issue and did not interfere with your believes of good practice. So I don't need to be trolled and/or lectured about good practices.  I consider your comments provocative and trolling. If you paid just a little attention to how GH works you might reconsider making such comments. You can always reopen your issue if you believe that it wasn't resolved and instead of complaining about **me** closing your issue, which I did not.  Is this clear?
