### ISSUE TITLE
[Bug] Failing rbpf-tests

### ISSUE THREAD

**Issue by ksolana** [solana-labs/move#66]
to repro:

$ cargo test -p move-mv-llvm-compiler --test rbpf-tests

```
error[E0412]: cannot find type `Option` in this scope
  --> /home/adityak/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.152/src/std_error.rs:45:25
   |
45 |     fn source(&self) -> Option<&(Error + 'static)> {
   |                         ^^^^^^ not found in this scope
   |
help: there is an enum variant `de::Unexpected::Option`; try using the variant's enum
   |
45 |     fn source(&self) -> de::Unexpected {
   |                         ~~~~~~~~~~~~~~


error[E0425]: cannot find value `None` in this scope
  --> /home/adityak/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.152/src/std_error.rs:46:9
   |
46 |         None
   |         ^^^^ not found in this scope

Some errors have detailed explanations: E0405, E0412, E0425, E0432, E0433, E0463, E0531.
error: could not compile `serde` due to 4284 previous errors
thread 'run_test::assert.move' panicked at 'running SBF cargo failed', language/tools/move-mv-llvm-compiler/tests/rbpf-tests.rs:135:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'thread 'run_test::abort.moverun_test::multi-module.move' panicked at '' panicked at 'Once instance has previously been poisonedOnce instance has previously been poisoned', ', language/tools/move-mv-llvm-compiler/tests/rbpf-tests.rslanguage/tools/move-mv-llvm-compiler/tests/rbpf-tests.rs::110110::1111

thread 'run_test::script.move' panicked at 'Once instance has previously been poisoned', language/tools/move-mv-llvm-compiler/tests/rbpf-tests.rs:test run_test::assert.move ... FAILED110
:11
test run_test::abort.move ... FAILED
test run_test::multi-module.move ... FAILED
test run_test::script.move ... FAILED

failures:
    run_test::assert.move
    run_test::abort.move
    run_test::multi-module.move
    run_test::script.move

test result: FAILED. 0 passed; 4 failed; 0 filtered out
```

**Comment by brson** [comment]
It's a strange error. This is happening while rbpf-tests is running cargo (from the sbf toolchain) to build the move-native crate. move-native is a no_std crate, which means all its dependencies should be configured not to use the standard library, but this error from inside serde seems to be related to compiling support for the std Error trait. So something here is confused about the configuration probably.

I haven't seen this yet, but it could have happened after a dependency changed in the lockfile, in this case probably `language/move-native/Cargo.lock`, or it could be related to being on a different version of SBF tools, which I see has had a new release since I last ran these tests.

**Comment by brson** [comment]
It could be that after an upgrade of something cargo is confused by its own metadata. The build artifacts for this particular build are in `language/tools/move-mv-llvm-compiler/tests/cargo-target-dir`. Deleting that dir may solve the problem.

**Comment by brson** [comment]
In the log output you posted the first error is:

```
building move-native runtime for sbf
   Compiling generic-array v0.14.6
   Compiling typenum v1.16.0
   Compiling keccak v0.1.3
   Compiling cfg-if v1.0.0
   Compiling serde v1.0.152
error[E0463]: can't find crate for `core`
  |
  = note: the `sbf-solana-solana` target may not be installed
  = help: consider downloading the target with `rustup target add sbf-solana-solana`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`
```

The build is failing because rustc can't find the core library for the sbf-solana-solana target. This probably indicates something broken in the sbf tools installation. the sbf tools should have a `rust/lib/rustlib/sbf-solana-solana/lib` directory, and that directory should contain a file like `libcore-0d7011e845091c1c.rlib`
