### ISSUE TITLE
[Bug] Compiling move-native v0.1.1 failed

### ISSUE THREAD

**Issue by ksolana** [solana-labs/move#82]
$ cd move/language/move-native && cargo build

```
Compiling move-native v0.1.1 (move/language/move-native)
error: no global memory allocator found but one is required; link to std or add `#[global_allocator]` to a static item that implements the GlobalAlloc trait

error: `#[panic_handler]` function required, but not found

error: language item required, but not found: `eh_personality`
  |
  = note: this can occur when a binary crate with `#![no_std]` is compiled for a target where `eh_personality` is defined in the standard library
  = help: you may be able to compile for a target that doesn't need `eh_personality`, specify a target with `--target` or in `.cargo/config`

error: `#[alloc_error_handler]` function required, but not found

note: use `#![feature(default_alloc_error_handler)]` for a default error handler

error: could not compile `move-native` due to 4 previous errors
```

**Comment by brson** [comment]
This is currently expected. move-native is a no-std crate and a library, so it doesn't set up the required global resources like an allocator that are needed to operate in typical host environments. Right now the only two environments it works in are its own test harness, and the rbpf vm.

This is also probably why I didn't add it to the workspace - because it doesn't build.

It should be possible to make the normal host build of move-native work, but the only reason to do so at the moment would be to add move-native to the workspace so that `cargo build` works.

**Comment by brson** [comment]
Though if you do want to run `cargo build` and have it work, doing so with the platform-tools cargo and `--target sbf-solana-solana` should work.
